<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound
/** @var $block \Icecube\EavManager\Block\Adminhtml\EavManager\Edit\Options\Options */

$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="admin__fieldset fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Options (Values of Your Attribute)')) ?></span>
    </legend><br />
    <div class="admin__control-table-wrapper" id="manage-options-panel" data-index="attribute_options_select_container">
        <table class="admin__control-table" data-index="attribute_options_select">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th">
                        <span><?= $block->escapeHtml(__('Is Default')) ?></span>
                    </th>
                    <?php foreach ($stores as $_store) :?>
                        <th<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) :?> class="_required"<?php endif; ?>>
                            <span><?= $block->escapeHtml(__($_store->getName())) ?></span>
                        </th>
                    <?php endforeach;
                    $storetotal = count($stores) + 3;
                    ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
                <tr>
                    <th colspan="<?= (int)$storetotal ?>" class="col-actions-add">
                        <?php if (!$block->getReadOnly()):?>
                            <button id="add_new_option_button" data-action="add_new_row"
                                    title="<?= $block->escapeHtml(__('Add Option')) ?>"
                                    type="button" class="action- scalable add">
                                <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                            </button>
                        <?php endif; ?>
                    </th>
                </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
</fieldset>
